create database LibraryManagement;

use LibraryManagement;
create table authors(
  AUTHOR_ID INT PRIMARY KEY,
  AUTHOR_NAME VARCHAR(50) NOT NULL,
  COUNTRY VARCHAR(15),
  DATEOFBIRTH DATE
);

CREATE TABLE CATEGORIES(
CATEGORY_ID INT PRIMARY KEY,
CATEGORY_NAME VARCHAR(15) NOT NULL,
DESCRIPTION VARCHAR(50)
);

CREATE TABLE BOOKS(
BOOK_ID INT PRIMARY KEY,
TITLE VARCHAR(20) NOT NULL,
ISBN VARCHAR(20) UNIQUE NOT NULL,
PUBLICATION_YEAR YEAR,
PUBLISHER VARCHAR(30),
AUTHOR_ID INT NOT NULL,
CATEGORY_ID INT,
LANGUAGE VARCHAR(10) NOT NULL,
EDITION INT NOT NULL,
TOTAL_PAGES INT,
FOREIGN KEY (AUTHOR_ID) REFERENCES authors(AUTHOR_ID),
FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(CATEGORY_ID)
);

CREATE TABLE MEMBERS(
MEMBER_ID INT PRIMARY KEY,
FIRST_NAME VARCHAR(15) NOT NULL,
LAST_NAME VARCHAR(15) NOT NULL,
GENDER VARCHAR(6),
DATE_OF_BIRTH DATE NOT NULL,
PHONE BIGINT,
EMAIL varchar(50) UNIQUE,
ADDRESS VARCHAR(50),
MEMBERSHIP_DATE DATE,
MEMBERSHIP_STATUS VARCHAR(15)
);

CREATE TABLE STAFF(
STAFF_ID BIGINT PRIMARY KEY,
FIRST_NAME VARCHAR(15) NOT NULL,
LAST_NAME VARCHAR(15) NOT NULL,
PHONE BIGINT UNIQUE NOT NULL,
EMAIL VARCHAR(50) UNIQUE NOT NULL,
ROLE VARCHAR(50),
HIRE_DATE DATE NOT NULL,
SALARY INT NOT NULL
);

CREATE TABLE BOOK_COPIES (
    COPY_ID INT PRIMARY KEY NOT NULL,
    BOOK_ID INT NOT NULL,
    BARCODE VARCHAR(50) UNIQUE,
    PURCHASE_DATE DATE,
    SHELF_LOCATION VARCHAR(30),
    STATUS VARCHAR(20),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID)
);

CREATE TABLE BORROW_RECORDS(
  BORROW_ID BIGINT PRIMARY KEY NOT NULL,
  MEMBER_ID INT NOT NULL,
  COPY_ID  INT NOT NULL,
  STAFF_ID BIGINT NOT NULL,
  BORROW_DATE DATE NOT NULL,
  DUE_DATE DATE NOT NULL,
  RETURN_DATE DATE,
  BORROW_STATUS VARCHAR(50) NOT NULL,
  FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID),
  FOREIGN KEY (COPY_ID) REFERENCES BOOK_COPIES(COPY_ID),
  FOREIGN KEY (STAFF_ID) REFERENCES STAFF(STAFF_ID)
);

CREATE TABLE RESERVATIONS(
RESERVATION_ID BIGINT PRIMARY KEY NOT NULL,
MEMBER_ID INT UNIQUE NOT NULL,
BOOK_ID INT UNIQUE NOT NULL,
RESERVATION_DATE DATE NOT NULL,
RESERVATION_STATUS VARCHAR(20),
EXPIRY_DATE DATE NOT NULL,
FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID),
FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID)
);

CREATE TABLE FINES(
FINE_ID BIGINT PRIMARY KEY NOT NULL,
BORROW_ID BIGINT NOT NULL,
FINE_AMOUNT INT,
FINE_REASON VARCHAR(20),
FINE_DATE DATE NOT NULL,
PAYMENT_STATUS VARCHAR(20),
PAYMENT_DATE DATE,
FOREIGN KEY (BORROW_ID) REFERENCES BORROW_RECORDS(BORROW_ID)
);









