USE librarymanagement;

-- AvailableBooks
CREATE VIEW AVAILABLEBOOKS AS
SELECT 
    B.BOOK_ID,
    B.TITLE,
    BC.COPY_ID,
    BC.SHELF_LOCATION
FROM BOOKS B 
JOIN BOOK_COPIES BC
ON B.BOOK_ID=BC.BOOK_ID
WHERE BC.STATUS='AVAILABLE';
SELECT*FROM AVAILABLEBOOKS;

-- ActiveMembers
CREATE VIEW ActiveMembers AS
SELECT
    MEMBER_ID,
    FIRST_NAME,
    LAST_NAME,
    PHONE,
    EMAIL,
    MEMBERSHIP_DATE
FROM MEMBERS
WHERE MEMBERSHIP_STATUS = 'Active';
SELECT * FROM ActiveMembers;

-- BorrowHistory
CREATE VIEW BORROWHISTORY AS
SELECT
    M.MEMBER_ID,
    M.FIRST_NAME,
    M.LAST_NAME,
    BR.BORROW_ID,
    BR.BORROW_DATE,
    BR.RETURN_DATE,
    BR.BORROW_STATUS,
    BC.BOOK_ID,
    BC.COPY_ID,
    B.TITLE
FROM BORROW_RECORDS BR
JOIN BOOK_COPIES BC
ON BC.COPY_ID=BR.COPY_ID
JOIN BOOKS B
ON B.BOOK_ID=BC.BOOK_ID
JOIN MEMBERS M
ON BR.MEMBER_ID=M.MEMBER_ID;
SELECT * FROM BORROWHISTORY;

-- FineSummary
CREATE VIEW FINESUMMARY AS
SELECT
      F.FINE_ID,
      F.FINE_AMOUNT,
      F.FINE_REASON,
      F.PAYMENT_STATUS,
      BR.BORROW_ID,
      BR.MEMBER_ID,
      BR.BORROW_DATE,
      M.FIRST_NAME,
      M.LAST_NAME,
      M.PHONE
FROM FINES F
JOIN BORROW_RECORDS BR
ON BR.BORROW_ID=F.BORROW_ID
JOIN MEMBERS M
ON M.MEMBER_ID=BR.MEMBER_ID;
SELECT*FROM FINESUMMARY;
	   
-- BookAuthorDetails
CREATE VIEW BOOKAUTHORDETAILS AS
SELECT
    B.BOOK_ID,
    B.TITLE,
    A.AUTHOR_NAME,
    C.CATEGORY_NAME,
    B.PUBLICATION_YEAR,
    B.PUBLISHER,
    B.LANGUAGE,
    B.EDITION,
    B.TOTAL_PAGES
FROM BOOKS B
JOIN AUTHORS A
ON B.AUTHOR_ID = A.AUTHOR_ID
JOIN CATEGORIES C
ON B.CATEGORY_ID = C.CATEGORY_ID;
SELECT*FROM BOOKAUTHORDETAILS;