use librarymanagement;
SELECT*FROM authors;
SELECT*FROM CATEGORIES;
SELECT * FROM BOOKS;
SELECT*FROM MEMBERS;
SELECT*FROM STAFF;
SELECT*FROM BOOK_COPIES;
SELECT * FROM BORROW_RECORDS;
SELECT * FROM RESERVATIONS;
SELECT*FROM FINES;

SELECT TITLE, PUBLISHER
FROM BOOKS;

SELECT FIRST_NAME, LAST_NAME
FROM MEMBERS;

SELECT AUTHOR_NAME, COUNTRY
FROM AUTHORS;

SELECT TITLE, TOTAL_PAGES
FROM BOOKS;

SELECT FINE_AMOUNT, PAYMENT_STATUS
FROM FINES;

SELECT TITLE FROM BOOKS
WHERE PUBLICATION_YEAR>2018;

SELECT TITLE FROM BOOKS
WHERE PUBLICATION_YEAR<2020;

-- 13. Members whose membership status is 'Active'.
SELECT FIRST_NAME FROM MEMBERS
WHERE MEMBERSHIP_STATUS = 'Active';

-- 14. Staff with salary greater than 40000.
SELECT STAFF_ID,FIRST_NAME FROM STAFF
WHERE SALARY>40000;

-- 15. Available book copies.
SELECT COPY_ID,BOOK_ID FROM BOOK_COPIES
WHERE STATUS='Available';

-- 16. English books.
SELECT TITLE FROM BOOKS 
WHERE LANGUAGE='English';

-- 17. Fines greater than 100.
SELECT FINE_ID,FINE_AMOUNT FROM FINES
WHERE FINE_AMOUNT>100;

-- 18. Returned borrow records.
SELECT BORROW_ID,MEMBER_ID,COPY_ID,BORROW_DATE,RETURN_DATE FROM BORROW_RECORDS
WHERE RETURN_DATE IS NOT NULL AND BORROW_STATUS='Returned';

-- 19. Pending reservations.
SELECT RESERVATION_ID,MEMBER_ID,BOOK_ID FROM RESERVATIONS
WHERE RESERVATION_STATUS='Pending';

-- 20. Members from Hyderabad.
SELECT MEMBER_ID,FIRST_NAME FROM MEMBERS
WHERE ADDRESS='Hyderabad';

-- Display all books ordered by TITLE in ascending order.
SELECT BOOK_ID,TITLE FROM BOOKS
ORDER BY TITLE ASC;

-- Display all books ordered by PUBLICATION_YEAR in descending order.
SELECT BOOK_ID,TITLE,PUBLICATION_YEAR FROM BOOKS
ORDER BY PUBLICATION_YEAR DESC;

-- Display all members ordered by FIRST_NAME alphabetically.
SELECT MEMBER_ID,FIRST_NAME FROM MEMBERS
ORDER BY FIRST_NAME;

-- Display all staff ordered by SALARY from highest to lowest.
SELECT STAFF_ID,FIRST_NAME FROM STAFF
ORDER BY SALARY DESC;

-- Display all fines ordered by FINE_AMOUNT from highest to lowest.
SELECT FINE_ID,FINE_AMOUNT FROM FINES
ORDER BY FINE_AMOUNT DESC;

-- Display all authors ordered alphabetically by AUTHOR_NAME.
SELECT AUTHOR_ID,AUTHOR_NAME FROM authors
ORDER BY AUTHOR_NAME;

-- Display all categories ordered alphabetically by CATEGORY_NAME.
SELECT CATEGORY_ID,CATEGORY_NAME FROM CATEGORIES
ORDER BY CATEGORY_NAME;

-- Display all book copies ordered by PURCHASE_DATE.
SELECT COPY_ID,BOOK_ID,PURCHASE_DATE FROM BOOK_COPIES
ORDER BY PURCHASE_DATE;

-- Display all borrow records ordered by BORROW_DATE.
SELECT BORROW_ID,MEMBER_ID,BORROW_DATE FROM BORROW_RECORDS
ORDER BY BORROW_DATE;

-- Display all members ordered by MEMBERSHIP_DATE.
SELECT MEMBER_ID,FIRST_NAME FROM MEMBERS
ORDER BY MEMBERSHIP_DATE;

-- Display all books whose TITLE starts with 'M'
SELECT BOOK_ID,TITLE FROM BOOKS
WHERE TITLE LIKE 'M%';

-- Display all authors whose AUTHOR_NAME contains the letter 'a'.
SELECT AUTHOR_NAME FROM authors
WHERE AUTHOR_NAME LIKE '%a%';

-- Display all members whose EMAIL contains 'gmail'.
SELECT MEMBER_ID,FIRST_NAME,EMAIL FROM MEMBERS
WHERE EMAIL LIKE '%gmail%';

-- Display all books whose PUBLISHER ends with 'Press'.
SELECT BOOK_ID,TITLE,PUBLISHER FROM BOOKS
WHERE PUBLISHER LIKE '%Press';

-- Display all books published between 2018 and 2022.
SELECT BOOK_ID,TITLE FROM BOOKS
WHERE PUBLICATION_YEAR BETWEEN 2018 AND 2022;

-- Display all staff members whose SALARY is between ₹30,000 and ₹50,000.
SELECT STAFF_ID,FIRST_NAME FROM STAFF 
WHERE SALARY BETWEEN 30000 AND 50000;

-- Display all members whose ADDRESS is Hyderabad, Mumbai, or Delhi.
SELECT MEMBER_ID,FIRST_NAME,ADDRESS FROM MEMBERS
WHERE ADDRESS IN ('Hyderabad','Mumbai','Delhi');

-- Display all books whose CATEGORY_ID is 2, 4, or 6.
SELECT BOOK_ID,TITLE,CATEGORY_ID FROM BOOKS
WHERE CATEGORY_ID IN (2,4,6);

-- Display all fines whose FINE_AMOUNT is between ₹50 and ₹150.
SELECT FINE_ID,BORROW_ID,FINE_AMOUNT FROM FINES
WHERE FINE_AMOUNT BETWEEN 50 AND 150;

-- Display all members whose FIRST_NAME ends with 'a'.
SELECT * FROM MEMBERS
WHERE FIRST_NAME LIKE '%a';

-- Count the total number of books.
SELECT SUM(BOOK_ID) FROM BOOKS; 

-- Count the total number of members.
SELECT SUM(MEMBER_ID) FROM MEMBERS;

-- Count the total number of staff members.
SELECT COUNT(STAFF_ID) FROM STAFF;

-- Find the highest salary among staff members.
SELECT MAX(SALARY) FROM STAFF;

-- Find the lowest fine amount.
SELECT MIN(FINE_AMOUNT) FROM FINES;

-- Find the average salary of staff members.
SELECT ROUND(AVG(SALARY)) FROM STAFF;

-- Find the average number of pages of all books.
SELECT ROUND(AVG(TOTAL_PAGES)) FROM BOOKS;

-- Find the total fine amount collected.
SELECT SUM(FINE_AMOUNT) FROM FINES;

-- Count the number of available book copies.
SELECT COUNT(BOOK_ID) FROM BOOK_COPIES;

-- Count the number of books in each category.
SELECT COUNT(BOOK_ID) FROM BOOKS
GROUP BY CATEGORY_ID;

