USE librarymanagement;
-- GROUP BY
-- Count the number of books in each category.
SELECT CATEGORY_ID,COUNT(BOOK_ID) FROM BOOKS
GROUP BY CATEGORY_ID;

-- Count the number of books written by each author.
SELECT AUTHOR_ID,COUNT(BOOK_ID) FROM BOOKS
GROUP BY AUTHOR_ID;

-- Count books based on language.
SELECT LANGUAGE,COUNT(BOOK_ID) FROM BOOKS
GROUP BY LANGUAGE; 

-- Count members according to membership status.
SELECT MEMBERSHIP_STATUS,COUNT(MEMBER_ID) FROM MEMBERS
GROUP BY MEMBERSHIP_STATUS;

-- Count staff members according to role.
SELECT ROLE,COUNT(FIRST_NAME) FROM STAFF
GROUP BY ROLE;

-- Count borrow records according to borrow status.
SELECT BORROW_STATUS,COUNT(BORROW_ID) FROM BORROW_RECORDS
GROUP BY BORROW_STATUS;

-- Count reservations according to reservation status.
SELECT COUNT(RESERVATION_ID),RESERVATION_STATUS FROM RESERVATIONS
GROUP BY RESERVATION_STATUS;

-- Count fines according to payment status.
SELECT COUNT(FINE_ID),PAYMENT_STATUS FROM FINES
GROUP BY PAYMENT_STATUS;

-- Find the average salary for each staff role.
SELECT AVG(SALARY),ROLE FROM STAFF
GROUP BY ROLE;

-- Find the average number of pages in each category.
SELECT ROUND(AVG(TOTAL_PAGES)),CATEGORY_ID FROM BOOKS
GROUP BY CATEGORY_ID;

-- HAVING
-- Display categories having more than one book.
SELECT CATEGORY_ID ,COUNT(BOOK_ID) FROM BOOKS
GROUP BY CATEGORY_ID
HAVING COUNT(BOOK_ID)>1;

-- Display authors who have written more than one book.
SELECT AUTHORS.AUTHOR_NAME,COUNT(BOOKS.BOOK_ID) 
FROM AUTHORS
JOIN BOOKS
ON AUTHORS.AUTHOR_ID=BOOKS.AUTHOR_ID
GROUP BY AUTHORS.AUTHOR_NAME
HAVING COUNT(BOOKS.BOOK_ID)>1;

-- Display publishers having more than one book.
SELECT PUBLISHER,COUNT(TITLE) FROM BOOKS
GROUP BY PUBLISHER
HAVING COUNT(TITLE)>1;

-- Display languages having more than one book.
SELECT LANGUAGE,COUNT(TITLE) FROM BOOKS
GROUP BY LANGUAGE
HAVING COUNT(TITLE)>1;

-- Display roles having more than one staff member.
SELECT ROLE,COUNT(STAFF_ID) FROM STAFF
GROUP BY ROLE
HAVING COUNT(STAFF_ID)>1;

-- Display members who borrowed more than one book.
SELECT COUNT(BORROW_RECORDS.MEMBER_ID),MEMBERS.FIRST_NAME,MEMBERS.LAST_NAME
FROM MEMBERS
LEFT JOIN BORROW_RECORDS
ON BORROW_RECORDS.MEMBER_ID=MEMBERS.MEMBER_ID
GROUP BY MEMBERS.MEMBER_ID
HAVING COUNT(BORROW_RECORDS.MEMBER_ID)>1;

-- Display categories whose average page count is greater than 300.
SELECT ROUND(AVG(BOOKS.TOTAL_PAGES)),CATEGORIES.CATEGORY_NAME
FROM CATEGORIES
JOIN BOOKS
ON BOOKS.CATEGORY_ID=CATEGORIES.CATEGORY_ID
GROUP BY CATEGORIES.CATEGORY_ID
HAVING AVG(BOOKS.TOTAL_PAGES)>300;

-- Display staff roles whose average salary exceeds ₹40,000.
SELECT ROUND(AVG(SALARY)),ROLE FROM STAFF
GROUP BY ROLE
HAVING AVG(SALARY)>40000; 

-- Display borrow statuses that occur more than once.
SELECT COUNT(BORROW_ID),BORROW_STATUS FROM BORROW_RECORDS
GROUP BY BORROW_STATUS
HAVING COUNT(BORROW_ID)>1;

-- Display payment statuses that occur more than once
SELECT COUNT(PAYMENT_STATUS),PAYMENT_STATUS FROM FINES
GROUP BY PAYMENT_STATUS
HAVING COUNT(PAYMENT_STATUS)>1;