use librarymanagement;
-- INNER JOIN
-- Display the book title along with the author name.
SELECT BOOKS.TITLE,AUTHORS.AUTHOR_NAME
FROM BOOKS
INNER JOIN AUTHORS
ON BOOKS.AUTHOR_ID=AUTHORS.AUTHOR_ID;

-- Display the book title along with its category name.
SELECT BOOKS.TITLE,CATEGORIES.CATEGORY_NAME
FROM BOOKS
INNER JOIN CATEGORIES
ON BOOKS.CATEGORY_ID=CATEGORIES.CATEGORY_ID;

-- Display the member's full name along with the borrow date and due date.
SELECT MEMBERS.FIRST_NAME,MEMBERS.LAST_NAME,BORROW_RECORDS.BORROW_DATE,BORROW_RECORDS.DUE_DATE
FROM MEMBERS
INNER JOIN BORROW_RECORDS
ON MEMBERS.MEMBER_ID=BORROW_RECORDS.MEMBER_ID;

-- Display the member name, book title, and borrow status.
SELECT MEMBERS.FIRST_NAME,MEMBERS.LAST_NAME,BOOKS.TITLE,BORROW_RECORDS.BORROW_STATUS
FROM MEMBERS
INNER JOIN BORROW_RECORDS
ON MEMBERS.MEMBER_ID=BORROW_RECORDS.MEMBER_ID
INNER JOIN BOOKS
ON MEMBERS.MEMBER_ID=BORROW_RECORDS.MEMBER_ID;

-- Display the staff member's name along with the books they issued.
SELECT STAFF.FIRST_NAME,BORROW_RECORDS.*
FROM STAFF
INNER JOIN BORROW_RECORDS
ON STAFF.STAFF_ID=BORROW_RECORDS.STAFF_ID;

-- Display the reservation details along with the member's name.
SELECT RESERVATIONS.*,MEMBERS.FIRST_NAME
FROM RESERVATIONS
INNER JOIN MEMBERS
ON RESERVATIONS.MEMBER_ID=MEMBERS.MEMBER_ID;

-- Display the reservation details along with the reserved book title.
SELECT RESERVATIONS.*,BOOKS.TITLE
FROM RESERVATIONS
INNER JOIN BOOKS
ON RESERVATIONS.BOOK_ID=BOOKS.BOOK_ID;

-- Display the fine amount, member name, and book title.
SELECT FINES.FINE_AMOUNT,MEMBERS.FIRST_NAME,MEMBERS.LAST_NAME,BOOKS.TITLE
FROM FINES
INNER JOIN BORROW_RECORDS
ON FINES.BORROW_ID=BORROW_RECORDS.BORROW_ID
INNER JOIN BOOK_COPIES
ON BORROW_RECORDS.COPY_ID=BOOK_COPIES.COPY_ID
INNER JOIN BOOKS
ON BOOKS.BOOK_ID=BOOK_COPIES.BOOK_ID
INNER JOIN MEMBERS
ON MEMBERS.MEMBER_ID=BORROW_RECORDS.MEMBER_ID
ORDER BY FINE_AMOUNT;

-- Display every book copy with its corresponding book title.
SELECT BOOKS.TITLE,BOOK_COPIES.*
FROM BOOKS
INNER JOIN BOOK_COPIES
ON BOOKS.BOOK_ID=BOOK_COPIES.BOOK_ID;

-- Display  title, author name, and category name together.
SELECT BOOKS.TITLE,AUTHORS.AUTHOR_NAME,CATEGORIES.CATEGORY_NAME
FROM BOOKS
INNER JOIN AUTHORS
ON AUTHORS.AUTHOR_ID=BOOKS.AUTHOR_ID
INNER JOIN CATEGORIES
ON CATEGORIES.CATEGORY_ID=BOOKS.CATEGORY_ID;

-- LEFT JOIN
-- Display all books, including books that have never been borrowed.
SELECT BOOKS.*,BORROW_RECORDS.*
FROM BOOKS
LEFT JOIN BOOK_COPIES
ON BOOKS.BOOK_ID=BOOK_COPIES.BOOK_ID
LEFT JOIN BORROW_RECORDS
ON BOOK_COPIES.COPY_ID=borrow_records.COPY_ID;

-- Display all members, including members who have never borrowed a book.
SELECT MEMBERS.*,BORROW_RECORDS.*
FROM MEMBERS
LEFT JOIN BORROW_RECORDS
ON BORROW_RECORDS.MEMBER_ID=MEMBERS.MEMBER_ID;

-- Display all authors, including authors who have not written any books.
SELECT AUTHORS.*,BOOKS.*
FROM AUTHORS
LEFT JOIN BOOKS
ON BOOKS.AUTHOR_ID=AUTHORS.AUTHOR_ID;

-- Display all categories, including categories that contain no books.
SELECT CATEGORIES.*,BOOKS.*
FROM CATEGORIES
LEFT JOIN BOOKS
ON CATEGORIES.CATEGORY_ID=BOOKS.CATEGORY_ID;

-- Display all staff members, including those who have never issued a book.
SELECT STAFF.*,BOOKS.*
FROM STAFF
LEFT JOIN BORROW_RECORDS
ON BORROW_RECORDS.STAFF_ID=STAFF.STAFF_ID
LEFT JOIN BOOK_COPIES
ON BOOK_COPIES.COPY_ID=BORROW_RECORDS.COPY_ID
LEFT JOIN BOOKS
ON BOOKS.BOOK_ID=BOOK_COPIES.BOOK_ID;


-- RIGHT JOIN
-- Display all authors and their books.


-- Display all categories and their books.
SELECT CATEGORIES.CATEGORY_NAME, BOOKS.TITLE
FROM BOOKS
RIGHT JOIN CATEGORIES
ON BOOKS.CATEGORY_ID = CATEGORIES.CATEGORY_ID;

-- Display all members and their borrow records.
SELECT MEMBERS.FIRST_NAME, BORROW_RECORDS.BORROW_ID, BORROW_RECORDS.BORROW_DATE, BORROW_RECORDS.RETURN_DATE
FROM BORROW_RECORDS
RIGHT JOIN MEMBERS
ON BORROW_RECORDS.MEMBER_ID = MEMBERS.MEMBER_ID;

-- Display all books and their reservation details.
SELECT BOOKS.TITLE, RESERVATIONS.RESERVATION_ID, RESERVATIONS.MEMBER_ID, RESERVATIONS.RESERVATION_DATE
FROM RESERVATIONS
RIGHT JOIN BOOKS
ON RESERVATIONS.BOOK_ID = BOOKS.BOOK_ID;

-- Display all borrow records and their fines.
SELECT BORROW_RECORDS.*, FINES.FINE_AMOUNT
FROM FINES
RIGHT JOIN BORROW_RECORDS
ON FINES.BORROW_ID = BORROW_RECORDS.BORROW_ID;

-- SELF JOIN
-- Display staff members who have the same role.
SELECT STAFF.*
FROM STAFF
JOIN STAFF AS STAFF2
ON STAFF.ROLE=STAFF2.ROLE
AND STAFF.STAFF_ID<STAFF2.STAFF_ID;

-- Display members living in the same city.
SELECT MEMBERS.*
FROM MEMBERS
JOIN MEMBERS AS MEMBERS2
ON MEMBERS.ADDRESS=MEMBERS2.ADDRESS
AND MEMBERS.MEMBER_ID < MEMBERS2.MEMBER_ID;
-- ORDER BY MEMBERS.FIRST_NAME;

-- Display books published by the same publisher.
SELECT BOOKS.*
FROM BOOKS
JOIN BOOKS AS BOOKS2
ON BOOKS.PUBLISHER=BOOKS2.PUBLISHER
AND BOOKS.BOOK_ID < BOOKS2.BOOK_ID;

-- Display authors belonging to the same country.
SELECT AUTHORS.*,AUTH.AUTHOR_NAME
FROM AUTHORS
JOIN AUTHORS AS AUTH
ON AUTHORS.COUNTRY=AUTH.COUNTRY
AND AUTHORS.AUTHOR_ID < AUTH.AUTHOR_ID;

-- Display books published in the same year.
SELECT BOOKS.*,BOO.TITLE
FROM BOOKS
JOIN BOOKS AS BOO
ON BOOKS.BOOK_ID=BOO.BOOK_ID
AND BOOKS.BOOK_ID < BOO.BOOK_ID;