use librarymanagement;

-- Create a procedure to display all books.
DELIMITER //
CREATE PROCEDURE BOOKS()
BEGIN
     SELECT * FROM BOOKS;
END //
DELIMITER ;

CALL BOOKS(); 

-- Display books by category.
DELIMITER //
CREATE PROCEDURE BYCATEGORY(IN PCATEGORY VARCHAR(50))
BEGIN
    SELECT B.BOOK_ID,B.TITLE,C.CATEGORY_ID,C.CATEGORY_NAME,B.ISBN
    FROM BOOKS B
    JOIN CATEGORIES C
    WHERE C.CATEGORY_ID=PCATEGORY;
END //
DELIMITER ;

CALL BYCATEGORY('Science');

-- Display books by author.
DELIMITER //
CREATE PROCEDURE BOOKSAUTHOR(IN AUTH VARCHAR(30))
BEGIN
    SELECT B.BOOK_ID,B.TITLE,B.CATEGORY_ID,A.AUTHOR_ID,A.AUTHOR_NAME
    FROM BOOKS B
    JOIN AUTHORS A
    ON B.AUTHOR_ID=A.AUTHOR_ID
    WHERE A.AUTHOR_NAME=AUTH;
END //
DELIMITER ;
CALL BOOKSAUTHOR('Julian Martinez');

-- Display active members.
DELIMITER //
CREATE PROCEDURE ACTIVE()
BEGIN 
     SELECT *
    FROM MEMBERS
    WHERE MEMBERSHIP_STATUS = 'Active';
END //

DELIMITER ;

CALL ACTIVE();


-- Display a member's borrow history.
DELIMITER //

CREATE PROCEDURE BORROWHISTORY(IN MID INT)
BEGIN
    SELECT BR.BORROW_ID,
           B.TITLE,
           BR.BORROW_DATE,
           BR.DUE_DATE,
           BR.RETURN_DATE,
           BR.BORROW_STATUS
    FROM BORROW_RECORDS BR
    JOIN BOOK_COPIES BC
    ON BR.COPY_ID = BC.COPY_ID
    JOIN BOOKS B
    ON BC.BOOK_ID = B.BOOK_ID
    WHERE BR.MEMBER_ID = MID;
END //

DELIMITER ;

CALL BORROWHISTORY(1001);

